const express = require('express');
const authRoutes = require('./authRoutes');
const branchRoutes = require('./branchRoutes');
const customerRoutes = require('./customerRoutes');
const employeeRoutes = require('./employeeRoutes');
const formRoutes = require('./formRoutes');
const receiptRoutes = require('./receiptRoutes');
const enquiryRoutes = require('./enquiryRoutes');
const dashboardRoutes = require('./dashboardRoutes');
const collectionRoutes = require('./collectionRoutes');
const inventoryRoutes = require('./inventoryRoutes');
const paymentRoutes = require('./paymentRoutes');
const expenseRoutes = require('./expenseRoutes');
const amcRoutes = require('./amcRoutes');
const uploadRoutes = require('./uploadRoutes');
const serviceRateRoutes = require('./serviceRateRoutes');
const notificationRoutes = require('./notificationRoutes');
const travelLogRoutes = require('./travelLogRoutes');
const purchaseRequestRoutes = require('./purchaseRequestRoutes');
const stockTransferRoutes = require('./stockTransferRoutes');
const hqAccountRoutes = require('./hqAccountRoutes');
const ledgerRoutes = require('./ledgerRoutes');
const taskAssignmentRoutes = require('./taskAssignmentRoutes');

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/branches', branchRoutes);
router.use('/customers', customerRoutes);
router.use('/employees', employeeRoutes);
router.use('/forms', formRoutes);
router.use('/receipts', receiptRoutes);
router.use('/enquiries', enquiryRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/collections', collectionRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/payments', paymentRoutes);
router.use('/expenses', expenseRoutes);
router.use('/amc', amcRoutes);
router.use('/upload', uploadRoutes);
router.use('/service-rates', serviceRateRoutes);
router.use('/notifications', notificationRoutes);
router.use('/travel-logs', travelLogRoutes);
router.use('/purchase-requests', purchaseRequestRoutes);
router.use('/stock-transfers', stockTransferRoutes);
router.use('/hq-account', hqAccountRoutes);
router.use('/ledger', ledgerRoutes);
router.use('/task-assignments', taskAssignmentRoutes);

module.exports = router;
